= Oh My Arch

一个用 Shell 编写的 Arch Linux 配置管理工具。
配合 Git 实现版本控制。

== 依赖

* openssh
* rsync
* sudo
* zsh

== 下载

[source, bash]
----
curl -sSL https://ghproxy.com/https://github.com/eastack/ohmyarch/archive/main.tar.gz | tar -zxv
----

== 使用

=== 命令格式

[source, bash]
----
./ohmyarch ACTION [APPNAME]...
----

=== 简单示例

比如我们想对 `zsh` 进行管理。
首先可以创建一个名为 `zsh` 的文件夹用来存储相关脚本。
[source, bash]
----
mkdir zsh
----

然后在 `zsh` 文件夹下创建一个名为 `setup` 的文件，在其中编写对应脚本。
.zsh/setup
[source, bash]
----
echo zsh install cuccess.
----

最后执行下面的命令便可以执行 `zsh/setup` 脚本。
[source, bash]
----
./ohmyarch setup zsh
----

=== 安装 Arch Linux

1. 设置环境变量
+
[source, bash]
----
export NAME='eastack'   # 用户名
export UPWD='12345'     # 用户密码
export RPWD='67890'     # ROOT密码
export DISK='/dev/sda'  # 系统安装磁盘
----
+
2. 执行脚本进行系统安装
+
NOTE: 脚本将会格式化 `DISK` 环境变量指定磁盘，使用前前请务必阅读脚本 `archlinux/install` 。
+
[source, bash]
----
./ohmyarch install archlinux
----
+
3. 重启进入新系统
+
[source, bash]
----
reboot
----

=== 备份还原

这里我们还以 `zsh` 为例，如果要管理其配置文件，则需要在 `zsh` 下创建 `.archives` 文件夹，再在其下创建任意命名的文件夹用来存储要备份的配置如文件、文件权限等。

1. 配置
+
然后将要进行管理文件的绝对路径添加到 `./zsh/.archives/main/file` 文件中
+
2. 备份
+
文件将保持其路径备份到 `./zsh/.archives/main` 目录下。
而其相关权限也被保存于 `./zsh/.archives/main/facl` 文件中。
+
[source, bash]
----
./ohmyarch backup zsh
----
+
3. 还原
+
将会还原文件内容和其相关权限信息。
+
[source, bash]
----
./ohmyarch restore zsh
----

如果不指定应用名称的话默认对所有应用执行操作

.比如将安装所有配置的应用
[source, bash]
----
./ohmyarch setup
----

== 待办

* [ ] 蓝牙键盘连接时自动执行 `~/.keymapping` https://wiki.archlinux.org/index.php/Udev_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)[Udev]
* [ ] asciinema 配置
* [ ] 触摸板手势
* [ ] `.xinitrc` 中 `dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY` 需要 `DISPLAY` 吗？
* [ ] 使用Python备份还原指定的idea配置字段（貌似 xslt + xsltproc 就可以了）
* [ ] ssh yubikey 啥的尽快弄好, key agent, 和备份
* [ ] gpg加密和gnome-keyring
* [ ] redshift 开机启动前需要启动定位服务
* [ ] tinc开机启动失败问题待排查
* [ ] datagrip setup 逻辑有问题，config文件丢失

== 片段

[source, bash]
----
sed -i "s/radix10/eastack/" $(ls ./*/.archives/*/facl)
ls -d ./*/.archives/*/home/radix10 | xargs -I file sh -c 'sudo mv file $(dirname file)/eastack'
----
