#!/usr/bin/env zsh

# make idempotent
test -f /usr/local/bin/datagrip && exit

setup jq

# download latest and unpack
RELEASE_API='https://data.services.jetbrains.com/products?code=DG&release.type=release'
DOWNLOAD_URL=$(curl $RELEASE_API | jq -r '.[0].releases[0].downloads.linux.link' | sed 's/jetbrains.com/jetbrains.8686c.com/')
DATAGRIP="$HOME/.local/share/datagrip"

mkdir -p $DATAGRIP
curl -Lf $DOWNLOAD_URL -o $DATAGRIP/datagrip.tar.gz
tar -zxvf $DATAGRIP/datagrip.tar.gz --strip-components=1 -C $DATAGRIP

DESKTOP_FILE_NAME='jetbrains-datagrip.desktop'

# create desktop entry
touch $DESKTOP_FILE_NAME

cat <<EOF > $DESKTOP_FILE_NAME
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ DATAGRIP Ultimate Edition
Icon=$HOME/.local/share/datagrip/bin/datagrip.svg
Exec="$HOME/.local/share/datagrip/bin/datagrip.sh" %f
Comment=Capable and Ergonomic IDE for JVM
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-datagrip
EOF

sudo xdg-desktop-menu install --mode system $DESKTOP_FILE_NAME
sudo xdg-desktop-menu forceupdate --mode system

rm -f $DESKTOP_FILE_NAME

# create command-line launcher
sudo ln -s $DATAGRIP/bin/datagrip.sh /usr/local/bin/datagrip
