#!/usr/bin/env zsh

# download latest and unpack
RELEASE_API='https://data.services.jetbrains.com/products?code=IIU&release.type=release'
DOWNLOAD_URL=$(curl $RELEASE_API | jq -r '.[0].releases[0].downloads.linux.link' | sed 's/jetbrains.com/jetbrains.8686c.com/')
IDEA="$HOME/.local/share/idea"

mkdir -p $IDEA
curl -Lf $DOWNLOAD_URL -o $IDEA/idea.tar.gz
tar -zxvf $IDEA/idea.tar.gz --strip-components=1 -C $IDEA

DESKTOP_FILE_NAME='jetbrains-idea.desktop'

# create desktop entry
touch $DESKTOP_FILE_NAME

cat <<EOF > $DESKTOP_FILE_NAME
[Desktop Entry]
Version=1.0
Type=Application
Name=IntelliJ IDEA Ultimate Edition
Icon=$HOME/.local/share/idea/bin/idea.svg
Exec="$HOME/.local/share/idea/bin/idea.sh" %f
Comment=Capable and Ergonomic IDE for JVM
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-idea
EOF

sudo xdg-desktop-menu install --mode system $DESKTOP_FILE_NAME
sudo xdg-desktop-menu forceupdate --mode system

rm -f $DESKTOP_FILE_NAME
