#!/usr/bin/env zsh

export CHSH=no
export RUNZSH=no
export KEEP_ZSHRC=yes
export REMOTE=https://gitee.com/radix10/ohmyzsh

sh -c "$(curl -fsSL https://gitee.com/radix10/ohmyzsh/raw/master/tools/install.sh)"

cd $ZSH
git remote set-url origin $REMOTE
