#!/usr/bin/env zsh

export CHSH=no
export RUNZSH=no
export KEEP_ZSHRC=yes
export REMOTE=https://ghproxy.com/https://github.com/ohmyzsh/ohmyzsh

sh -c "$(curl -fsSL https://ghproxy.com/https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
