#!/usr/bin/env zsh

sh -c 'curl -sSfLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://ghproxy.com/https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

nvim --headless -u $HOME/.config/nvim/plug.vim +PlugInstall +qall
